name: Approve PR
author: jgautsch
description: "A GitHub action for approving PRs"
branding:
  icon: "git-pull-request"
  color: green
inputs:
  github-token:
    description: "GitHub Token"
    required: true
  pr-number:
    description: "Pull Request number"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
