name: CI
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Approve Pull Request
        uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          pr-number: ${{github.event.number}}
